name: orb-mysteries # you probably want to 'snapcraft register <name>'
base: core22 # the base snap is the execution environment for this snap
version: '1.0.0' # just for humans, typically '1.2+git' or '1.3.2'
title: Ancient Orb Mysteries
summary: Match magical orbs to solve puzzles.
description: Discover hidden secrets by combining ancient orbs in this puzzle-solving adventure filled with surprises.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

apps:
  orb-mysteries:
    command: bin/orb-mysteries-bin
    extensions: [gnome]
    plugs:
      - network
      - unity7
      - network-status

layout:
  /usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/webkit2gtk-4.1:
    bind: $SNAP/gnome-platform/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/webkit2gtk-4.0

parts:
  orb-mysteries:
    plugin: dump
    source: .
    organize:
      orb-mysteries-bin: bin/
